/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acara;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matthew.d
 */
public class FormAcara extends javax.swing.JFrame {

    /**
     * Creates new form FormPilihtiket
     */
    
    ArrayList<String> eventList;
    public String e_id;
    public Date e_startDate;
    public Date e_endDate;
    public String u_id;
    FormLogin parent;
    
    public FormAcara(FormLogin parentLogin) {
        initComponents();
        parent=parentLogin;
        u_id = parent.idAccount;

        eventList = (ArrayList<String>) getEventList();
        refreshTable();
    }
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTableListAcara.getModel();
        model.setRowCount(0);
        
        for (String stringEvent : eventList) {
            String[] eventDetails = stringEvent.split("~");
            model.addRow(eventDetails);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPilihTiketDisini = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListAcara = new javax.swing.JTable();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabelPilihTiketDisini.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPilihTiketDisini.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabelPilihTiketDisini.setText("Event Ticket Reservation");

        jTableListAcara.setBackground(new java.awt.Color(153, 204, 255));
        jTableListAcara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Deskripsi", "Start Date", "End Date", "Available", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableListAcara.setGridColor(new java.awt.Color(0, 0, 0));
        jTableListAcara.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableListAcara.setSelectionForeground(new java.awt.Color(51, 255, 102));
        jTableListAcara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListAcaraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListAcara);

        button1.setBackground(new java.awt.Color(153, 204, 255));
        button1.setLabel("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPilihTiketDisini)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPilihTiketDisini)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListAcaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListAcaraMouseClicked
        int row = jTableListAcara.getSelectedColumn();
        
        if (row >= 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) jTableListAcara.getModel();
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
                e_id = model.getValueAt(row, 0).toString();
                e_startDate = formatter.parse(model.getValueAt(row, 3).toString());
                e_endDate = formatter.parse(model.getValueAt(row, 4).toString());
                
                FormProcess detailForm = new FormProcess(e_id, u_id, e_startDate, e_endDate);
                detailForm.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(FormAcara.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTableListAcaraMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabelPilihTiketDisini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListAcara;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> getEventList() {
        com.ticket.services.TicketWebService_Service service = new com.ticket.services.TicketWebService_Service();
        com.ticket.services.TicketWebService port = service.getTicketWebServicePort();
        return port.getEventList();
    }

}
